name: Add workflow logs to PR comments

on:
  pull_request:
    

jobs:
  add-logs-to-pr-comments:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write 
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      #contents: write
      #pull-requests: write
      #repository-projects: write
      #id-token: write
      - name: checkout
        uses: actions/checkout@v4              
      - name: Add log TFPlan
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Hello world ! :wave:
