name : Terraform - Plan dev
on:
  pull_request:
permissions:
  id-token: write
  contents: read  
env:
  TERRAFORM_VERSION: "1.6.3"  
  TFPLAN_ID: pr-${{ github.event.pull_request.number }}-${{ github.repository_id }}
  ENV: "dev"
concurrency: 
  group: deploy-workflow
jobs:
  terraform-check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
     
  plan-dev:
    runs-on: ubuntu-latest
    
    needs: terraform-check
    steps:
        - name: checkout
          id: checkout
          uses: actions/checkout@v4
        - name: HashiCorp - Setup Terraform
          id: setup-terraform
          uses: hashicorp/setup-terraform@v2.0.3
          with:
            terraform_version: ${{ env.TERRAFORM_VERSION }}

        - name: Terraform Init
          id: init
          run: make init
        - name: Terraform Plan
          id: plan
          run: make plan
        - name: Upload tfplan
          id: upload-tfplan
          uses: actions/upload-artifact@v4
          with:
            name: ${{ env.TFPLAN_ID }}-dev-tfplan
            path: terraform/plan.tfplan
            if-no-files-found: error